name: Detailed report with PWA
on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Running Page Speed Insights
      uses: jakepartusch/psi-action@v1.3
      id: psi
      with:
        url: "https://cartimdraluc.github.io/Cartimpedia/"
        threshold: 70
        strategy: desktop
