name: Pagespeed Insights
on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Running Page Speed Insights
      uses: jakepartusch/psi-action@v1.3
      id: psi
      with:
        url: "https://cartimdraluc.github.io/Cartimpedia/"
        threshold: 70
        strategy: desktop
        
    - uses: actions/checkout@v2 # This is a premade github action
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - name: Create local changes
      run: | # Have to be sure a folder is present if not, make it
          mkdir -p ${RESULTSFOLDER}
          curl "${PSURL}/?url=${HOST}" > ./${RESULTSFOLDER}/${PSRDESKTOP}.svg
    - name: Commit files 
      run: |
        git add .
        git config --local user.email "actions@github.com"
        git config --local user.name "github-actions[bot]"
        git diff --quiet && git diff --staged --quiet || git commit -am "Updated Pagespeed results"
    - name: Push changes
      uses: ad-m/github-push-action@master # This is a premade github action
      with:
        branch: ${{ github.ref }}
