name: Get Pagespeed results
on:
  workflow_dispatch:

jobs:
  getpsresults:
    env:
      HOST: https://cartimdraluc.github.io/Cartimpedia/
      PSURL: https://pagespeed-insights.herokuapp.com
      PSRDESKTOP: psresultdesktop
      PSRMOBILE: psresultmobile
      RESULTSFOLDER: reports
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2 # This is a premade github action
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - name: Create local changes
      run: | # Have to be sure a folder is present if not, make it
          mkdir -p ${RESULTSFOLDER}
          curl "${PSURL}/?url=${HOST}" > ./${RESULTSFOLDER}/${PSRDESKTOP}.svg
          curl "${PSURL}/?url=${HOST}&strategy=mobile" > ./${RESULTSFOLDER}/${PSRMOBILE}.svg
    - name: Commit files 
      run: |
